(in-package :xul-test)

(define-component text-box-output ()
  ((output :initform "(no input yet)"
	   :accessor output))
  (:render (comp)
	   (<:label (<:style= "width:10em")
		    (<:value= "Input: "))
	   (<:hbox (<:pack= :center)
		   (<:description (output comp)))))	   

(define-component text-boxes-showcase ()
  ()
  (:initialize (comp)
	       (add-component comp 'text-box-output (make-instance 'text-box-output)))
  (:render (comp)
	   (with-child-components (text-box-output) comp
	     (<:vbox
	       (<:flex= 1)
	       (<:style= "overflow: auto")
	       (<:description "XUL Textboxes")
	       (<:hbox (<:align= :center)
		       (<:label (<:style= "width:10em")
				(<:value= "Default"))
		       (<:text-box
			 (on-input=* (value)
			   (setf (output text-box-output)
				 value))))
	       (<:hbox (<:align= :center)
		       (<:label (<:style= "width:10em")
				(<:value= "Disabled"))
		       (<:text-box (<:disabled= t)
				   (<:value= "Disabled")
				   (on-input=* (value)
				     (setf (output text-box-output)
					   value))))
	       (<:hbox (<:align= :center)
		       (<:label (<:style= "width:10em")
				(<:value= "Readonly"))
		       (<:text-box (<:readonly= t)
				   (<:value= "Readonly")
				   (on-input=* (value)
				     (setf (output text-box-output)
					   value))))
	       (<:hbox (<:align= :center)
		       (<:label (<:style= "width:10em")
				(<:value= "Max length of 20"))
		       (<:text-box (<:maxlength= 20)
				   (<:size= 20)
				   (on-input=* (value)
				     (setf (output text-box-output)
					   value))))
	       (<:hbox (<:align= :center)
		       (<:label (<:style= "width:10em")
				(<:value= "Password"))
		       (<:text-box (<:type*= :password)
				   (on-input=* (value)
				     (setf (output text-box-output)
					   value))))
	       (<:hbox (<:align= :center)
		       (<:label (<:style= "width:10em")
				(<:value= "Multiline"))
		       (<:text-box (<:multiline= t)
				   (<:rows= 7)
				   (<:cols= 20)
				   (on-input=* (value)
				     (setf (output text-box-output)
					   value))))
	       (<:hbox (<:align= :center)
		       (render text-box-output))))))
